# Generated by Django 3.2 on 2021-05-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('wht', 'White'), ('blc', 'Black'), ('red', 'Red'), ('blu', 'Blue')], default='wht', max_length=20),
        ),
    ]
