# Generated by Django 3.2 on 2021-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('RED', 'Red'), ('BLUE', 'Blue')], max_length=20),
        ),
    ]
