# Generated by Django 3.2 on 2021-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('wht', 'White'), ('blc', 'Black'), ('red', 'Red'), ('blu', 'Blue')], default='wht', max_length=20),
        ),
    ]
