# Generated by Django 3.2 on 2021-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active_basket',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
